version: '3.9'
services:
  app:
    container_name: home_library_service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - network
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
  postgres:
    container_name: home_library_service_db
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - ${PORT_DB}:${PORT_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  pgdata:
