version: '3.9'
services:
  api:
    container_name: home_library_service
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    networks:
      - network
    command: npm run start:dev
    volumes:
      - app:/usr/app
      - /usr/app/node_modules
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
